### ISSUE TITLE
[Vanilla] Multiple item sended by main will cause crash

### ISSUE THREAD

**Issue by palfibeni** [WowLegacyCore/HermesProxy#19]
2 item sended correctly, in two different letter, but 3 causes crash, and the 3rd item wont be sent.

**Comment by MaxtorCoder** [comment]
Any crashlog you can show us?

**Comment by palfibeni** [comment]
Hermes does not log anything else just: `WorldClient | Socket Closed By Server`
I see no relevant in the classic_era/Logs either :/

**Comment by ratkosrb** [comment]
I cant understand what you mean. Can you record a video of the crash?

**Comment by schgabor** [comment]
He means that sending 2 items in mail is working fine, but sending 3 or more items crashes the client after clicking on send. Despite that the mail will be delivered but only the first 2 items arrive, the remaining wasn't attached to the mail at all.

**Comment by 0blu** [comment]
Can reproduce https://www.youtube.com/watch?v=URG35PpnTJY
This is probably caused by the fact that each item is send in a new mail, so if you send 5 items you try to send 5 mails in a really short time.
The server probably thinks that you are a bot and kicks you.
When testing on my local server I see `[AntiFlood]` messages (but I am on an admin account and thus get not kicked).

To solve this HermesProxy needs to send all items within one mail.

**Comment by 0blu** [comment]
"fixed" in 8a9b49b030c8fb2013daffc38dfdd7f84270c15f
