### ISSUE TITLE
Entering EPL disconnects you

### ISSUE THREAD

**Issue by Fearyii** [WowLegacyCore/HermesProxy#233]
**Describe the bug**
No matter what character i try to get in that zone i get constantly disconnected, No need for a screenshot even if I am not on a GM account whenever i enter the zone i just get disconnected.

**Game Server**
Hellground Brotalnia Repack

**Hermes Proxy Version**
3.6.0 [TBC]

**Comment by ratkosrb** [comment]
I know what the reason is most likely. The Naxxramas transport is probably spawned as a normal gameobject, not as a transport, and that will cause client to disconnect. It was an issue in vmangos too, but i fixed it there. Try using a cmangos TBC repack instead (a recent one, not 5 years old), and it should be fine there.

**Comment by Fearyii** [comment]
> I know what the reason is most likely. The Naxxramas transport is probably spawned as a normal gameobject, not as a transport, and that will cause client to disconnect. It was an issue in vmangos too, but i fixed it there. Try using a cmangos TBC repack instead (a recent one, not 5 years old), and it should be fine there.

Yes it only was for the repack when its fixed its not a problem.
