### ISSUE TITLE
HermesProxy Detection

### ISSUE THREAD

**Issue by Novivy** [WowLegacyCore/HermesProxy#299]
Does there is any way to detect server side that the player is using hermesproxy/1.14 client?

Do you send any info that we could use to identify it? like a special packet/opcode or something?

 There are a lot of issues with this client and we want to warn players if they are using it.

**Comment by 0blu** [comment]
You could check if a player is connecting with a "MACOS" client, because there is no way a real player is using this client.
But if someone changes this in their HermesConfig there is no easy way to detect a Hermes player.

Keep in mind that banning HermesProxy by default might upset some people, because for example playing on vanilla servers with a ARM based Mac is only possible via HermesProxy other methods might result in 15 fps.

**Comment by Novivy** [comment]
Thank you for your quick answer. We won't ban it but just warn players that there are issues, like custom items not loading/displaying and elevators getting out of sync or transports not appearing sometimes

**Comment by Fearyii** [comment]
> Thank you for your quick answer. We won't ban it but just warn players that there are issues, like custom items not loading/displaying and elevators getting out of sync or transports not appearing sometimes

Hey there was just wondering is that project/server you are talking is it already a thing or a very early thing, since i have not heard for a new vanilla server coming soon?
