### ISSUE TITLE
please take a look at the github link below-thank you

### ISSUE THREAD

**Issue by kalypto89** [WowLegacyCore/HermesProxy#89]
Describe the bug
https://github.com/xod-wow/LiteButtonAuras/issues/9

Game Server
Everlook

**Hermes Proxy Version**
HermesProxy Windows 23-06-2022

**Comment by ratkosrb** [comment]
The 1.12 server does not send who is the caster of an aura, so it's not possible for Hermes to set the caster guid in the aura update packet, in order to highlight auras casted by you. Hermes is a merely a translation layer for the packets, converting the structure from the old format to the new. We don't have access to the internal server memory in order to fetch the aura caster and fill in this part of the packet properly.
